### ISSUE TITLE
Handle non-square textures

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/Sunwell#14]
I haven't actually tested it because http://hearthstonelabs.com/cards#lang=enUS is down but TB_SPT_Minion2 has a non-square texture (1024x2048)

Also see https://github.com/HearthSim/joust/issues/122

**Comment by Paratron** [comment]
The page works fine for me. In which way is it down for you?

**Comment by jleclanche** [comment]
base.js is not loading.

**Comment by jleclanche** [comment]
Beneath the Grounds may be affected (`AT_035`)

**Comment by jleclanche** [comment]
Closing since Beneath the Grounds is not affected, and the texture was squarified.

http://hearthstonelabs.com/cards#lang=enUS;hero=rogue;search=b;detail=AT_035
