### ISSUE TITLE
Add Karazhan background logo

### ISSUE THREAD

**Issue by beheh** [HearthSim/Sunwell#17]

**Comment by ErikJson** [comment]
I spent some time exercising my lacking graphic skills today and managed to make some icons that look ok. I won't submit a PR with them as they still look a bit too different from the rest of the icons, but feel free to use them while we wait.

My fork is [here](https://github.com/knugen/sunwell), and [this is the commit](https://github.com/knugen/sunwell/commit/dd9b031b7ab6d2b26cbc226d70c04cecb890a678).

**Comment by jleclanche** [comment]
Yeah, looks fine to merge, though I'd really like to take care of #19 so that we don't have to mess around with custom assets like that.

**Comment by ErikJson** [comment]
Yeah I saw that one, would be great :)

In the meantime I went ahead and created https://github.com/HearthSim/sunwell/pull/20, after all.
