### ISSUE TITLE
Do not duplicate assets for spell/weapon watermarks

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/Sunwell#19]
I'm not sure how Hearthstone does it. @andburn do you know?

**Comment by andburn** [comment]
A shader blends a grayscale image with the description texture. It should be possible to do similar blending with css or with canvas directly.
![naxxicon](https://cloud.githubusercontent.com/assets/5419653/19273284/db750014-8fc3-11e6-972a-e89bca564e2c.png)

**Comment by andburn** [comment]
The icons are in `textures0` named `NaxxIcon`, `KaraIcon` etc., with the exception of classic its `shared/Set1_Icon`.
