### ISSUE TITLE
Clipping ellipse on spell cards

### ISSUE THREAD

**Issue by Lett1** [HearthSim/Sunwell#22]
![Failed Clipping](https://puu.sh/srO4b/eba8be42b6.png)

The area used to clip normal minion card images will sometimes persist into spell cards, causing the grey area above. Happens in both chrome and safari on osx.

**Comment by Lett1** [comment]
Can apparently fixed be adding `ctx.BeginPath()` line 998. Needs a bit more testing.

**Comment by malakai97** [comment]
@Lett1 Could you be more specific about this fix, with code or a patch?
