### ISSUE TITLE
Set up Sunwell on HearthSim CDN

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/Sunwell#25]
I removed sunwell.min.js from the repo so I'll be moving it to build automatically off our build server.

**Comment by Paratron** [comment]
I'd like to keep it in the repo so people can use it as a direct download and drop-in source. Thats why I put it there in the first place. Having a single CDN for every library in your project is bad practice.

**Comment by jleclanche** [comment]
@Paratron I'm not sure what you mean; it'll be autogenerated on our build server now, and it'll be made available on the CDN. How is that not drop-in source?

Take Joust for example: https://joust.hearthsim.net/branches/master/joust.js

I'll be doing this ASAP (already working on it); but we can't ask contributors to always regenerate sunwell.min.js. It'll go out of date all the time and increase the size of the repository (git doesn't deal well with big blobs).

**Comment by Paratron** [comment]
I mean that we should have the minified and up to date version of the sunwell.js stored in the repo for people who dont want to use the CDN or dont want to look for a different download source than github. Please put it back into the repo as I did it originally.

**Comment by jleclanche** [comment]
I already gave you a heads up about this on skype before blizzcon and it wasn't a problem then, why is it a problem now?

Asking contributors to regenerate sunwell.min.js all the time is not reasonable. The CDN will provide something that is automatically built and compiled *on push* so that we don't ever have to deal with it again. People who want a drop-in source can use that.

If you want downloads off Github then we can start doing releases, that sounds reasonable.

**Comment by jleclanche** [comment]
The minified file is now available [here](https://sunwell.hearthsim.net/branches/master/sunwell.js). It should update automatically.
