### ISSUE TITLE
Directly set mana/atk/health color

### ISSUE THREAD

**Issue by beheh** [HearthSim/Sunwell#3]
We'd like to directly be able to set the mana/attack/health colors (negative/positive/neutral = red/green/white) without having to rely on the internal (stateful) mechanism. The main motivation is using this in Joust, where the colors can be deduced by the default card values and other tags, such as health/max_health.

As an example, it's currently not easy to set the health on a minion effected by equality - it's health might be lower than it's default health, but it should be white since the current health is equal to the max health. Compare this to a minion though that has been noramlly attacked, and has it's current health set to one - it should be red.

**Comment by Paratron** [comment]
Implemented and done :)
