### ISSUE TITLE
Add a prettier default texture

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/Sunwell#32]
With support for arbitrary cards nearly complete, we're still missing a better looking default texture.

![image](https://cloud.githubusercontent.com/assets/235410/21447747/53d60ea2-c8e2-11e6-88a2-011bdd01bb36.png)

I figure we might as well add this in Sunwell itself, but we'd need the texture to be the same license as Sunwell (or even more permissive).
Anyone wants to take a crack at it? @andburn feeling inspired? :)

**Comment by andburn** [comment]
Nothing comes to mind right now, but I'll have a think about it 🤔

**Comment by jleclanche** [comment]
I've removed the "missing texture" for now, it's just grey atm.

**Comment by jleclanche** [comment]
I actually think it's fine as grey for now.
