### ISSUE TITLE
Non-latin fonts are incorrect

### ISSUE THREAD

**Issue by ksk-waqs** [HearthSim/Sunwell#33]
Hello! Thank you for a wonderful script!
Very cool thing, though - thank you!

1. This version of the script is not working (24 Dec 2016)
2. Russian fonts look horrible on http://hearthstonelabs.com/sunwell. (Maybe use BenguiatBoldITC and FranklinGothicURWConMed?)
3. How can I render a large number of cards on one page? (Do not write the text by hand?)

**Comment by jleclanche** [comment]
![image](https://user-images.githubusercontent.com/235410/37914073-088fd346-311f-11e8-9b37-70aa84863952.png)

![image](https://user-images.githubusercontent.com/235410/37914108-1dea8bdc-311f-11e8-9a8c-c599cf278d18.png)
vs.
![image](https://user-images.githubusercontent.com/235410/37914243-6bb10292-311f-11e8-8e0f-7222b28c4c53.png)
