### ISSUE TITLE
Sunwell on the HearthSim CDN gives a 404 error

### ISSUE THREAD

**Issue by alitch** [HearthSim/Sunwell#44]
The following link is included in the readme, but only leads to a 404 page [https://sunwell.hearthsim.net/branches/master/sunwell.js](https://sunwell.hearthsim.net/branches/master/sunwell.js)

I can't find any references to Sunwell on the hearthsim website, so I'm not sure if the url is incorrect or if the issue lies elsewhere.

**Comment by beheh** [comment]
The URL has changed to https://sunwell.hearthsim.net/branches/master/sunwell.cdn.min.js. Thanks for the report!
