### ISSUE TITLE
Readjust font sizes

### ISSUE THREAD

**Issue by beheh** [HearthSim/Sunwell#45]
They've been outdated since the layer rework.

**Comment by beheh** [comment]
They're still slightly to small as of The Witchwood/Monster Hunt release.

**Comment by beheh** [comment]
I'm also not sure why I get completely different font sizes on my machine compared to Lambda - need to investigate, so that I have reproducable font sizes to fix this issue.

**Comment by jleclanche** [comment]
Are you using Sunwell or [sunwell-lambda](https://github.com/HearthSim/sunwell-lambda)? with sunwell-lambda I reliably get exactly the same results.

**Comment by joolean** [comment]
Closing: Low urgency.
