### ISSUE TITLE
Properly render Bold+Italic

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/Sunwell#46]
Cards: Lesser Onyx Spellstone, Lesser Sapphire Spellstone, Lesser Emerald Spellstone.

**Comment by beheh** [comment]
![grafik](https://user-images.githubusercontent.com/929769/33717815-964e5118-db5b-11e7-96df-0608e4e2f058.png)

What's the issue (apart from the missing HearthstoneJSON data)?

**Comment by jleclanche** [comment]
**Deathrattle** should be italic (cf. ingame)
