### ISSUE TITLE
Implement SPELLS_COST_HEALTH graphics (Cho'gall)

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/Sunwell#5]
Example: https://www.youtube.com/watch?v=0IhK1Xkj9VU&t=4m33s

![image](https://cloud.githubusercontent.com/assets/235410/14935933/065429e4-0eec-11e6-80ae-f9423ff93de1.png)

**Comment by Paratron** [comment]
Now implemented through `{costHealth: true}`.
