### ISSUE TITLE
Implement golden card frames

### ISSUE THREAD

**Issue by Paratron** [HearthSim/Sunwell#6]

**Comment by jleclanche** [comment]
@Paratron Do you still have this on your plate?

**Comment by Paratron** [comment]
Yes it is - along with the webGL rendering :)

**Comment by jleclanche** [comment]
@Paratron I think golden card frames should be available without introducing the webgl dependency. In other words, have a premium=true argument for the static mode which just changes the frame to be golden.

**Comment by jleclanche** [comment]
The latest patch updated some golden class card frames.

**Comment by beheh** [comment]
This has been done.
