### ISSUE TITLE
Card text are cropped in the detailled view 

### ISSUE THREAD

**Issue by Shipow** [HearthSim/Sunwell#7]
![image](https://cloud.githubusercontent.com/assets/235410/14939431/26dfe94c-0f4f-11e6-9dfe-30fa22af723c.png)

Chrome: Version 50.0.2661.86 (64-bit) Mac OS 10.11.2

**Comment by Paratron** [comment]
Yeah, MacOS (and iOS) handle the fonts strangely different. I have fixed this already for iOS - will look into MacOS, too. Thanks for the heads up.

**Comment by Lett1** [comment]
This might be fixed by setting the baseline of the bodyfont to "middle" instead of "hanging". That fixed it for me on Chrome on macOS.

**Comment by beheh** [comment]
@Lett1 Can you make a PR?
