### ISSUE TITLE
Text layout issues

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/Sunwell#9]
![image](https://cloud.githubusercontent.com/assets/235410/15236691/e7186da4-18cf-11e6-8421-634feb50fbb1.png)

http://hearthstonelabs.com/cards#lang=deDE;cost=10;set=OG;detail=OG_133

Reference screenshot in-game:

![image](https://cloud.githubusercontent.com/assets/235410/15236714/196e4e5e-18d0-11e6-81fe-286c0e86e104.png)

**Comment by jleclanche** [comment]
Similar issue with Y'Shaarj:

![image](https://cloud.githubusercontent.com/assets/235410/15236747/643091ae-18d0-11e6-96bc-39eceeff9792.png)

![image](https://cloud.githubusercontent.com/assets/235410/15236750/67bf0990-18d0-11e6-8ffb-cf87ea54efc7.png)

**Comment by Paratron** [comment]
Hm, the N'Zoth text looks fine for me on hs-labs. I am pretty sure this is due to the body font used. I need to investigate some more.

**Comment by jleclanche** [comment]
Going to make this the master bug for text layout issues.

The Caverns Below:

https://art.hearthstonejson.com/v1/render/latest/enUS/256x/UNG_067.png

![image](https://cloud.githubusercontent.com/assets/235410/24690380/24cbf2ae-19d5-11e7-97bb-52de3dada028.png)

Awaken the Makers:

https://art.hearthstonejson.com/v1/render/latest/enUS/256x/UNG_940.png

![image](https://cloud.githubusercontent.com/assets/235410/24690396/378f1ca4-19d5-11e7-946f-d4dbc6b56227.png)

**Comment by jleclanche** [comment]
Open the Waygate:

https://art.hearthstonejson.com/v1/render/latest/enUS/256x/UNG_028.png

![image](https://cloud.githubusercontent.com/assets/235410/24690403/4c4ba95a-19d5-11e7-9b2d-a26384227051.png)

The Marsh Queen:

https://art.hearthstonejson.com/v1/render/latest/enUS/256x/UNG_920.png

![image](https://cloud.githubusercontent.com/assets/235410/24690417/595c41cc-19d5-11e7-900b-3d5251054080.png)

**Comment by jleclanche** [comment]
Gadgetzan Jouster:

https://art.hearthstonejson.com/v1/render/latest/enUS/256x/AT_133.png

![image](https://cloud.githubusercontent.com/assets/235410/24690480/b3f45a48-19d5-11e7-85ba-057713ca6112.png)

**Comment by jleclanche** [comment]
Kalimos:
![image](https://cloud.githubusercontent.com/assets/235410/24821018/da72208a-1bf4-11e7-84ef-604ee31ccfb3.png)

**Comment by jleclanche** [comment]
Closing this as most of these have been fixed and #35 should take care of the rest, if any.
